name: Python Applications

on:
  push:
    branches: [ "main" ]

jobs:
  workflow:
    uses: arjunpt/python-reusable-cicd/.github/workflows/cicd.yml@main
    with:
      python-version: "3.10"
      requirements-path: "src/requirements.txt"
      test-path: "src/test/test.py"