name: Python Applications

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: arjunpt/python-reusable-cicd/.github/workflows/reusable-python.yml@main
    with:
      python-version: "3.10"
      requirements-path: "src/requirements.txt"
